- tests/manual/theme.html
- tests/manual/theme.js
- theme/components/dropdown.scss
- theme/components/editor.scss
- theme/components/list.scss
- theme/helpers/_rounded.scss
- theme/helpers/_zindex.scss
- theme/theme.scss
Related to https://github.com/ckeditor/ckeditor5-ui-default/issues/12.
> t/ckeditor5-ui-default/12: Implement dropdown component

- theme/components/editor.scss
> t/46: Made the .ck-editor always relatively positioned.

- theme/helpers/_colors.scss
- theme/helpers/_shadow.scss
> t/52 Fixed: ck-dropshadow() looks bad on dark backgrounds.

- theme/components/balloonpanel.scss
- theme/components/button.scss
- theme/components/dropdown.scss
- theme/components/editor.scss
- theme/components/inputtext.scss
- theme/helpers/_colors.scss
- theme/helpers/_shadow.scss
- theme/helpers/_states.scss
Closes #50.
Closes https://github.com/ckeditor/ckeditor5-editor-classic/issues/27.
> t/50b: Unified focus outline/border/shadows strategy across the UI.

- tests/manual/theme.js
- theme/components/toolbar.scss
Fix: Toolbar separator and new line CSS classes incompatible with naming guidelines. Also used `ToolbarSeparatorView` in the manual test. Closes #76.
---
* Requires https://github.com/ckeditor/ckeditor5-ui/pull/160.
> t/76: Fixed toolbar separator and new line CSS classes incompatible with naming guidelines

- theme/components/list.scss
- theme/helpers/_colors.scss
Other: Removed tick symbol from active list item, used inverted background and text colors instead. Closes #82.
---
Closes https://github.com/ckeditor/ckeditor5-heading/issues/65.
> T/82: Removed tick symbol from active list item, used inverted background and text colors instead

- theme/components/editor.scss
- theme/components/panel/balloonpanel.scss
Other: Implemented `.ck-editor-toolbar-container` class to control balloon panels containing editor toolbars. Closes #89.
> t/89:  Implemented `.ck-editor-toolbar-container` class to control balloon panels containing editor toolbars

- theme/components/panel/balloonpanel.scss
Fixed: Balloon panel content should not be misaligned when it's narrow. Closes #69.
> t/69: Balloon panel content should not be misaligned when it's narrow

- theme/components/button.scss
- theme/components/dropdown.scss
- theme/helpers/_states.scss
Fix: Tooltips for disabled buttons should not be dimmed. Closes #70.
BREAKING CHANGE: `.ck-disabled` is no longer available as a standalone class due to differences in the implementation of the disabled state among the UI components. Use a mixin instead `.your-class.ck-disabled { @include ck-disabled; }` to keep the previous functionality (reduced `opacity`) or provide a custom implementation of the state.
> t/70: Tooltips for disabled buttons should not be dimmed

- theme/components/toolbar/toolbar.scss
Fix: Toolbar items should not collapse when the toolbar is floating. Closes #93.
> t/93: Toolbar items should not collapse when the toolbar is floating

- theme/components/panel/balloonpanel.scss
Other: The `.ck-balloon-panel` arrow styles need an update after recent `BalloonPanelView` refactoring. Closes #95.
BREAKING CHANGE: The (`.ck-balloon-panel_arrow_nw`–`.ck-balloon-panel_arrow_ne`) and (`.ck-balloon-panel_arrow_sw`–`.ck-balloon-panel_arrow_se`) class pairs have been swapped to reflect the actual placement of the arrow with respect to the balloon.
> Other: The .ck-balloon-panel_arrow styles need update after recent BalloonPanelView refactoring

- theme/components/reset.scss
Fix: The `.ck-reset` class should set `word-wrap` to `break-word` to make sure long words do not overflow. Closes #105.
---
* Also closes https://github.com/ckeditor/ckeditor5/issues/462.
> t/105: The .ck-reset class should set word-wrap to break-word to make sure long words do not overflow

- tests/manual/theme.html
- tests/manual/theme.js
- theme/components/tooltip.scss
Other: Refactored tooltip styles to allow tooltips which are no longer pseudo-elements. Closes #103.
> t/103: Refactored tooltip styles to allow tooltips which are no longer pseudo-elements

- theme/components/editor.scss
Fix: Contextual toolbar container's arrow should have the same color as the toolbar. Closes #111.
> t/111: Contextual toolbar container's arrow should have the same color as the toolbar

- theme/ckeditor5-ui/components/editorui/editorui.css
Other: Style `ck-button_with-text` instead of styling every dropdown button in toolbar. Closes #122.
---
> Style `ck-button_with-text` instead of styling every dropdown button in toolbar.

- theme/ckeditor5-ui/components/editorui/editorui.css
Fix: First child of editable should always have a top margin to make sure the content is separated. Closes #116. Closes ckeditor/ckeditor5-ui#351.
> t/116: First child of editable should always have top margin

- theme/ckeditor5-ui/components/editorui/editorui.css
Fix: SplitButton state `isOn` is not properly shown. Closes #131.
> Fix: SplitButton state `isOn` is not properly shown.

- theme/ckeditor5-ui/globals/_colors.css
Other: Replaced the gradient with a solid color in the editor toolbar. Closes ckeditor/ckeditor5#805.
----
> t/ckeditor5/805: Replaced the gradient with a solid color in the editor toolbar

- theme/ckeditor5-link/linkactions.css
- theme/ckeditor5-ui/components/button/button.css
- theme/ckeditor5-ui/components/dropdown/splitbutton.css
- theme/ckeditor5-ui/components/inputtext/inputtext.css
- theme/ckeditor5-ui/globals/_colors.css
- theme/ckeditor5-ui/globals/_reset.css
- theme/ckeditor5-ui/globals/_spacing.css
- theme/theme.css
Other: Increased the spacing in the toolbar by making the buttons bigger. Unified rendering of several components. Closes ckeditor/ckeditor5#820.
---
* Requires https://github.com/ckeditor/ckeditor5-theme-lark/pull/137.
> t/ckeditor5/820: Increased the spacing in the toolbar

- theme/ckeditor5-ui/components/inputtext/inputtext.css
- theme/ckeditor5-ui/globals/_focus.css
Fix: The input focus outline should not overwhelm the surrounding form. Closes ckeditor/ckeditor5#815.
---
> t/ckeditor5/815: The input focus outline should not overwhelm the surrounding form

- theme/ckeditor5-ui/components/editorui/editorui.css
Fix: A lone paragraph should be vertically centered in the editor. Closes ckeditor/ckeditor5#847.
---
Also increased the top and bottom margins to make them slightly bigger than left/right editable padding
> t/ckeditor5/847: A lone paragraph should be vertically centered in the editor

- theme/ckeditor5-ui/components/dropdown/splitbutton.css
Other: Improved the visual styles of the split button when hovered or open. Closes #134.
---
* Requires https://github.com/ckeditor/ckeditor5-ui/pull/373.
> T/134: Improved the visual styles of the split button when hovered or open

- theme/ckeditor5-ui/globals/_colors.css
- theme/ckeditor5-ui/globals/_shadow.css
Other: Improved panel toolbar/balloon panel shadow. Closes https://github.com/ckeditor/ckeditor5/issues/818.
---
> Improved shadow visibility (changed opacity).

- theme/ckeditor5-ui/components/dropdown/dropdown.css
- theme/ckeditor5-ui/components/dropdown/listdropdown.css
- theme/ckeditor5-ui/components/dropdown/splitbutton.css
- theme/ckeditor5-ui/components/list/list.css
Other: Removed common (left bottom & top corner) border-radius of dropdown button & panel. Closes [ckeditor/ckeditor5#816](https://github.com/ckeditor/ckeditor5/issues/816).
---
> t/ckeditor5/816: Fixed border-radius of active dropdown button & panel.

- theme/ckeditor5-ui/components/icon/icon.css
Other: Fixed the coloring issue with the multi-color icons. Additionally, moved the visual `.ck-icon` styles from `ckeditor5-ui`. Closes #148.
---
* Added the `IconView#fillColor` observable which handles the coloring of `.ck-icon__fill`.
* Made the `ButtonView#IconView` always present, so highlight can easily bind the `#fillColor`
* Made the highlight use the `IconView#fillColor` API instead of weak CSS inheritance hacks.
* https://github.com/ckeditor/ckeditor5-ui/pull/374
* https://github.com/ckeditor/ckeditor5-highlight/pull/12
> t/148b: Moved the visual .ck-icon styles from ckeditor5-ui.

- theme/ckeditor5-link/link.css
Other: Enlarged background in `.ck-link_selected`. Closes #155.
> Enlarged link's highlight background.

- theme/ckeditor5-link/link.css
Feature: Made the link form buttons thicker with a fill color and no background (see ckeditor/ckeditor5#810).
> t/ckeditor5/810: Made the link form buttons thicker with a fill color and no background.

- docs/_snippets/examples/custom.css
- docs/framework/guides/theme-customization.md
- tests/manual/inverted.html
- tests/manual/theme.js
- theme/ckeditor5-link/link.css
- theme/ckeditor5-ui/components/button/button.css
- theme/ckeditor5-ui/globals/_colors.css
Feature: Implemented `.ck-button_save` and `_cancel` classes with distinctive colors (see ckeditor/ckeditor5-image#187). 
Updated the inverted theme manual test and the theme customization guide.
---
> t/ckeditor5-image/187: Implemented .ck-button_save and _cancel classes with distinctive colors.

- theme/ckeditor5-link/link.css
- theme/ckeditor5-ui/globals/_colors.css
Fix: The selected link element should not resemble the native selection. Closes #159.
> t/159: The selected link element should not resemble the native selection

- theme/ckeditor5-link/linkactions.css
Fix: Unified different padding between steps in the link panel. Closes #165.
---
It's not a pixel perfect solution, but now there is no such big "dancing effect".
> Fixed difference of padding between steps in the link panel.

- theme/ckeditor5-image/imageuploadicon.css
Feature: Added styles for upload complete icon (see https://github.com/ckeditor/ckeditor5-image/issues/204).
---
Requires: https://github.com/ckeditor/ckeditor5-image/pull/205
> Added styles for upload complete icon

- theme/ckeditor5-ui/components/toolbar/blocktoolbar.css
Feature: Added BlockToolbar styles. Closes https://github.com/ckeditor/ckeditor5-ui/issues/391.
---
Part of https://github.com/ckeditor/ckeditor5-ui/pull/392.
> Feature: Added BlockToolbar styles.

- theme/ckeditor5-table/tableediting.css
- theme/ckeditor5-widget/widget.css
Internal: Moved table editing styles from ckeditor5-table. Decreased the specificity of the widget's nested editable styles to make it possible to style tables as a content (see ckeditor/ckeditor5-table#2). Partially fixes ckeditor/ckeditor5-table#29.
---
* A piece of https://github.com/ckeditor/ckeditor5-table/pull/45
> t/ckeditor5-table/2: Improvements and refactoring to the table styles

- theme/ckeditor5-ui/components/editorui/editorui.css
Fix: The arrow of the balloon holding a toolbar should have the same background color as the toolbar. Closes #178.
> t/178: The arrow of the balloon holding a toolbar should have the same background color as the toolbar

- theme/ckeditor5-table/tableediting.css
Fix: The table cell selection highlight is broken on merged cells. Closes ckeditor/ckeditor5-table#69. Closes ckeditor/ckeditor5-table#29
---
* Finally the table cell selection is not broken anymore :)
* See https://github.com/ckeditor/ckeditor5-table/issues/69#issuecomment-399073685 for browsers comparison of available solutions.
> Fix: The table cell selection highlight is broken on merged cells.

- docs/_snippets/examples/custom.css
- docs/framework/guides/theme-customization.md
- tests/manual/iconset.js
- tests/manual/inverted.html
- theme/ckeditor5-ui/components/button/button.css
- theme/ckeditor5-ui/components/dropdown/dropdown.css
- theme/ckeditor5-ui/components/dropdown/listdropdown.css
- theme/ckeditor5-ui/components/inputtext/inputtext.css
- theme/ckeditor5-ui/components/list/list.css
- theme/ckeditor5-ui/globals/_colors.css
- theme/ckeditor5-ui/globals/_focus.css
- theme/ckeditor5-ui/mixins/_button.css
Other: Used a solid `box-shadow` to indicate the `:focus` state of the `.ck-button` (also `.ck-input`). Obsoleted the background color change on `.ck-button:focus` to avoid situations when a focused button looks like an active one (see ckeditor/ckeditor5-ui#394).
BREAKING CHANGE: Various color variables `--ck-color-button-...-focus` have been renamed to `--ck-color-button-...-hover`.
---
A piece of https://github.com/ckeditor/ckeditor5-ui/pull/422.
> t/ckeditor5-ui/394: Used a solid `box-shadow` to indicate the `:focus` state of the `.ck-button`

- theme/ckeditor5-ui/components/dropdown/dropdown.css
Fix: `DropdownPanelView` panel should properly display overflowed content. Added `--ck-dropdown-panel-max-height` CSS variable to handle maximum height of panel. Closes https://github.com/ckeditor/ckeditor5/issues/952
---
After:
> Added maximum height of `.ck-dropdown__panel`.

- theme/ckeditor5-ui/components/button/switchbutton.css
Fix: Switch button should be animated properly in Microsoft Edge. Closes https://github.com/ckeditor/ckeditor5-ui/issues/433.
> [Edge] Switch button is animated properly in Edge

- tests/manual/tickets/189/1.html
- tests/manual/tickets/189/1.js
- tests/manual/tickets/189/1.md
- tests/manual/tickets/189/assets/iframe-content.html
- tests/manual/tickets/189/assets/iframe-content.js
- theme/ckeditor5-ui/components/button/button.css
Fix: `ck-button` should ignore default `-webkit-appearance`. Closes #189.
---
Various CSS frameworks (e.g. bootstrap) is styling button-like elements, that's why we need to reset them:
```css
button,
html [type="button"], 
[type="reset"],
[type="submit"] {
-webkit-appearance: button;
}
```
> Fix: `ck-button` should ignore default `-webkit-appearance.`

- theme/ckeditor5-ui/components/inputtext/inputtext.css
Fix: Removed the initial transform property of the text input with an error to allow the shake animation in Safari. Closes ckeditor/ckeditor5-ui#443.
> t/ckeditor/ckeditor5-ui/443: Removed the initial transform property of the text input with an error to allow the shake animation in Safari

- theme/ckeditor5-table/tableediting.css
- theme/ckeditor5-ui/globals/_colors.css
Fix: Improved visibility of selected link inside the table cell. Closes https://github.com/ckeditor/ckeditor5-link/issues/204.
---
I had some doubts about placing new color. I'm not so sure if this (`tableediting.css`) is better place than global directory with colors - `theme-lark/globals/_colors.css`.
> Improved visibility of selected link inside table cell.

- theme/ckeditor5-ui/components/icon/icon.css
Only override the fill for elements that don't declare one.
Closes #206
> Don't set fill for icons that set declare it

- theme/ckeditor5-table/tableediting.css
Fix: Table selection handler should not be truncated if it is a first-child in the block quote or the content. Closes https://github.com/ckeditor/ckeditor5-block-quote/issues/28.
---
1. [Check table inside table case - fiddlejs demo](https://jsfiddle.net/8rzk7axb/1/) 
2. I've checked it on Edge and actually `calc()` with CSS Variables works fine (even adding `em` to the `px`!)
> Truncating table selection handler 

- theme/ckeditor5-table/tableediting.css
- theme/ckeditor5-widget/widget.css
Internal: Renamed the `.ck-widget_selectable` class to `.ck-widget_with-selection-handler` for better semantics. Made the selection handler crop fix introduced in #214 generic for all widgets (see ckeditor/ckeditor5-widget#66).
---
Requires https://github.com/ckeditor/ckeditor5-widget/pull/67.
> t/ckeditor5-widget/66: Renamed the `.ck-widget_selectable` class to `.ck-widget_with-selection-handler`

- theme/ckeditor5-ui/globals/_colors.css
Other: Background of hover list should has proper contrast. Closes #219.
---
> Background of hover list should has proper contrast

- theme/ckeditor5-ui/components/toolbar/toolbar.css
Fix: Vertical toolbar items should have no border-radius. Closes #168.
---
You can test it in alignment feature MTs.
> t/168: Fix: Vertical toolbar items should have no border radius.

- theme/ckeditor5-ui/components/dropdown/splitbutton.css
Fix: Background behavior of splitbutton in read-only mode. Closes ckeditor/ckeditor5#943.
> Fix css of splitbutton in readonly mode

- theme/ckeditor5-link/linkform.css
- theme/ckeditor5-ui/components/button/switchbutton.css
- theme/ckeditor5-ui/globals/_colors.css
Feature: Introduced styles for `LinkFormView` with manual decorators. Closes https://github.com/ckeditor/ckeditor5-link/issues/186.
---
Required: https://github.com/ckeditor/ckeditor5-link/pull/222
> Introduced styles for `LinkFormView` with manual decorators.

- theme/ckeditor5-ui/components/tooltip/tooltip.css
Fix: Tooltips should not render blurry in LoDPI environments. Closes ckeditor/ckeditor5#1802.
> t/ckeditor5/1802: Tooltips should not render blurry in LoDPI environments.

- theme/ckeditor5-ui/components/list/list.css
Other: Introduced to-do list styles (moved from ckeditor5-list repository). Closes https://github.com/ckeditor/ckeditor5-list/issues/146. Closes https://github.com/ckeditor/ckeditor5-list/issues/136
---
1) Fixed selecting "unchecked" list element on Safari
2) Fixed vertical align of checkmark with larger fonts
3) Fixed WCAG contrast of checkmark (now passing 3.0)
> Introduced to-do list styles

- theme/ckeditor5-ui/components/list/list.css
Internal: Moved to–do list styles away from the UI List component styles. Moved styles to ckeditor5-list (see ckeditor/ckeditor5-list#147).
---
Requires https://github.com/ckeditor/ckeditor5-list/pull/158
> t/ckeditor5-list/147: Moved to–do list styles away from the UI List component styles

- theme/ckeditor5-widget/widget.css
Internal: Aligned widget class names to the refactoring in ckeditor5-widget (see ckeditor/ckeditor5-widget#99).
---
Requires https://github.com/ckeditor/ckeditor5-widget/pull/110.
> t/ckeditor5-widget/99: Aligned widget class names to the refactoring in ckeditor5-widget

- theme/ckeditor5-font/fontcolor.css
- theme/ckeditor5-table/inserttable.css
- theme/ckeditor5-ui/components/button/button.css
- theme/ckeditor5-ui/components/colorgrid/colorgrid.css
- theme/ckeditor5-ui/components/list/list.css
- theme/ckeditor5-ui/globals/_colors.css
- theme/ckeditor5-ui/globals/_focus.css
Fix: Enabled additional box-shadow on `.ck-button` to meet WCAG AA recommendations. Adjusted the color of the `--ck-color-focus-border` for the same reason (editables, widget selection, etc.). Closes ckeditor/ckeditor5#5580.
Also: 
* Optimized the color gird component for WCAG AA. 
* Imported insert table UI styles from ckeditor5-table (code refactoring).
* Improved the table UI contrast and accessibility.
BREAKING CHANGE: The `--ck-color-focus-shadow` custom property is now `--ck-color-focus-outer-shadow`.
---
Requires:
* https://github.com/ckeditor/ckeditor5-table/pull/223
* https://github.com/ckeditor/ckeditor5-ui/pull/527
---
> i/5580: Various improvements to the UI to match WCAG AA requirements

- tests/manual/theme.html
- tests/manual/theme.js
- theme/ckeditor5-ui/components/button/button.css
Feature: Implemented styles for `.ck-button` with a keystroke preview (see ckeditor/ckeditor5#5782).
---
Part of https://github.com/ckeditor/ckeditor5-ui/pull/531.
> i/5782: Implemented styles for .ck-button with a keystroke preview.

- theme/ckeditor5-restricted-editing/restrictedediting.css
Internal: Moved restricted-editing package styles to theme-lark. Closes ckeditor/ckeditor5#5793.
---
Part of https://github.com/ckeditor/ckeditor5-restricted-editing/pull/4.
> i/5793: Moved restricted-editing package styles to theme-lark

- theme/ckeditor5-restricted-editing/restrictedediting.css
Fix: Removed ck- prefix. Closes https://github.com/ckeditor/ckeditor5/issues/5899
> I/5899: Remove ck- prefix from classes

- theme/ckeditor5-restricted-editing/restrictedediting.css
Fix: Set default cursor in restricted editing mode while restricted editing exceptions still have text cursor when you hover over them. Closes ckeditor/ckeditor5#5992.
> i/5992: Set default cursor in restricted editing mode

- tests/manual/iconset.js
- tests/manual/theme.html
- tests/manual/theme.js
- theme/ckeditor5-table/form.css
- theme/ckeditor5-table/formheader.css
- theme/ckeditor5-table/formrow.css
- theme/ckeditor5-table/tablecellproperties.css
- theme/ckeditor5-table/tableproperties.css
- theme/ckeditor5-ui/components/toolbar/toolbar.css
Feature: Brought styles for various UI views: the compact toolbar, table form, table form row and header, table cell properties form, and table properties form (see ckeditor/ckeditor5/issues/6112).
---
A piece of https://github.com/ckeditor/ckeditor5-table/pull/232
> I/6112: Brought styles for various UI views (compact toolbar, table forms)

- theme/ckeditor5-restricted-editing/restrictedediting.css
Other: Add hover state for all exeptions and fix width for collapsed exception in restricted editing. Closes https://github.com/ckeditor/ckeditor5/issues/5829.
> I/5829: Enhance restricted editing feature styling

- theme/ckeditor5-table/tableform.css
Feature: Added styles for rich error messages in the table and table cell properties forms (see ckeditor/ckeditor5#6131).
---
Piece of: https://github.com/ckeditor/ckeditor5-table/pull/238
> i/6131: Added styles for rich error messages in the table and table cell properties forms

- theme/ckeditor5-restricted-editing/restrictedediting.css
Fix: Pointer inside the restricted editing exception should be set to `text` for all children. Closes ckeditor/ckeditor5#6272.
---
Pointer for all of the elements inside the restricted editing mode should be set to `default` except for restricted editing exceptions and their children, where it should be set to `text`.
The fix also contains code refactoring for the styles.
> i/6272: Fix styles for restricted editing cursor behaviour

- theme/ckeditor5-table/tableediting.css
Other: Prevented the background color change of the focused element in table. Closes ckeditor/ckeditor5#6229.
> i/6229: Inherit background color for focused element in table

- theme/ckeditor5-ui/components/formheader/formheader.css
Other: Moved part of the form header component styling to the theme-lark. See ckeditor/ckeditor5#6507.
-- 
Master PR: https://github.com/ckeditor/ckeditor5-ui/pull/550
> i/6507: Clean up the form header styling
