ckeditor/ckeditor5-theme-lark

tests/manual/theme.html, tests/manual/theme.js, theme/components/icon.scss
=> t/3: Allow dynamically colored icons created with Template class

theme/components/icon.scss
=> t/5: Icons do not inherit cursor style.

theme/components/editor.scss
As in https://github.com/ckeditor/ckeditor5/issues/135.
Closes #8 .
=> T/8: Provide skin for Classic Creator

tests/manual/theme.js
A part of https://github.com/ckeditor/ckeditor5-ui/pull/39
=> t/ckeditor5-ui/3: An utility to extend existing templates

tests/manual/theme.html
=> Added reset for dropdown section in manual test.

tests/manual/theme.js, theme/components/button.scss
Fixes: https://github.com/ckeditor/ckeditor5-ui-default/issues/21
Depends on: https://github.com/ckeditor/ckeditor5-ui-default/pull/22
=> Added `noText` option to ButtonView.

tests/manual/theme.js, theme/components/dropdown.scss
Part of https://github.com/ckeditor/ckeditor5-ui/issues/26.
=> T/ckeditor5 ui/26: Review our approach to MVVM

tests/manual/theme.html, theme/components/button.scss, theme/components/toolbar.scss
=> Visually separated toolbar items with an empty space.

tests/manual/theme.js
Fixes: https://github.com/ckeditor/ckeditor5/issues/211
Related to:
- https://github.com/ckeditor/ckeditor5-utils/pull/49
- https://github.com/ckeditor/ckeditor5-undo/pull/20
- https://github.com/ckeditor/ckeditor5-ui-default/pull/32
- https://github.com/ckeditor/ckeditor5-typing/pull/25
- https://github.com/ckeditor/ckeditor5-engine/pull/530
- https://github.com/ckeditor/ckeditor5-delete/pull/13
- https://github.com/ckeditor/ckeditor5-basic-styles/pull/9
=> Changed const to lower case.

tests/manual/theme.js, theme/components/button.scss
Fixes https://github.com/ckeditor/ckeditor5-ui-default/issues/30
Depends on https://github.com/ckeditor/ckeditor5-ui-default/pull/31
=> Changed button parameter.

theme/components/dropdown.scss
=> Fixed label width in the Dropdown to avoid uncontrolled size changes.

.jshintrc, tests/.jshintrc, tests/manual/theme.js
=> Turn JSHint browser setting to false.

tests/manual/theme.html
=> Fixed path to ckeditor.css

tests/manual/theme.js, theme/components/button.scss, theme/components/editor.scss
=> t/14: Disabled hover and active states for disabled button

tests/manual/theme.js
Requires https://github.com/ckeditor/ckeditor5-ui/pull/100.
=> t/38: Updated Lark after the removal of Controller class.

theme/components/label.scss
=> t/44 Added styles for .ck-voice-label class.

theme/components/label.scss
=> t/48: Fixed the voice-label prefix.

theme/components/button.scss, theme/components/editor.scss, theme/components/inputtext.scss, theme/helpers/_states.scss
=> t/50 Normalized focus outline of .ck-editor__editable.

theme/components/balloonpanel.scss, theme/components/editor.scss
=> t/54: Created styles for contextual toolbar.

theme/components/button.scss, theme/components/dropdown.scss, theme/components/editor.scss, theme/components/tooltip.scss, theme/helpers/_fonts.scss, theme/theme.scss
=> t/56: Added styles for rich tooltips. Enabled tooltips in button component.

tests/manual/theme.js
Depends on: https://github.com/ckeditor/ckeditor5-ui-default/pull/141
Fixes #57
=> Aligned manual test to latest Icon component API.

theme/components/button.scss
=> t/36: Fixed cursor inconsistency when hovering a button with icon in Chrome.

tests/manual/theme.html, tests/manual/theme.js
=> t/63: Re–enabled a limited set of icons in theme's manual test.

theme/components/dropdown.scss, theme/components/list.scss
=> t/71: Optimized theme to support focused items in lists and dropdowns.

theme/helpers/_states.scss
Other: Extracted "ck-hidden" CSS class to ckeditor5-ui. Closes #78.
=> t/78: Extracted ck-hidden class to ckeditor5-ui.

theme/components/list.scss, theme/helpers/_shadow.scss
Feature: Added styles for active list items. Closes #80.
=> T/80: Added styles for active list items

theme/components/panel/balloonpanel.scss
Other: Updated class names after the refactoring in BalloonPanelView class. Closes #84.
---
Requires https://github.com/ckeditor/ckeditor5-ui/pull/197.
=> t/84: Updated class names after the refactoring in BalloonPanelView class. Closes #84.

theme/components/button.scss, theme/components/dropdown.scss
Fix: Disabled buttons should have a different look. Closes #98.
=> t/98: Disabled buttons should have a different look

tests/manual/theme.html, tests/manual/theme.js, theme/components/inputtext.scss
Feature: Added styles for UI components in read–only state. Closes #100.
=> t/100: Added styles for UI components in read–only state

docs/_snippets/examples/custom.css, docs/_snippets/examples/extras.css, docs/framework/guides/theme-customization.md, tests/manual/inverted.html, theme/ckeditor5-basic-styles/code.css, theme/ckeditor5-ui/globals/_reset.css, theme/ckeditor5-widget/widget.css
Other: Changed hex/rgb format to hsl/a in some css variables. Closes #124 .
=> t/124: Standarized colors to hsl/a format.

docs/_snippets/examples/theme-lark.js, package.json
Docs: Enabled EasyImage in editor snippet. Read more https://github.com/ckeditor/ckeditor5/issues/789.
=> Enabled EasyImage in editor snippet

tests/manual/theme.html, tests/manual/theme.js, theme/ckeditor5-ui/components/dropdown/dropdown.css, theme/ckeditor5-ui/components/dropdown/splitbutton.css, theme/ckeditor5-ui/components/dropdown/toolbardropdown.css
Tests: Manual test are not updated to the newest dropdown API. Closes #129.
---
=> Fix: Manual test are not updated to the newest dropdown API.

docs/_snippets/examples/theme-lark.js, tests/manual/inverted.js
Other: Align code to the changes in naming UI components & commands.
---
* Minor PR - Check: https://github.com/ckeditor/ckeditor5-alignment/pull/25.
=> Other: Align code to the changes in naming UI components & commands.

theme/ckeditor5-ui/components/button/button.css
Other: Disabled outline in `.ck-button`. Closes #157 .
=> Disabled buttons outline.

theme/ckeditor5-editor-classic/classiceditor.css, theme/ckeditor5-ui/components/editorui/editorui.css, theme/ckeditor5-widget/widget.css
Other: Updated the classic editor and the editorui styles to the latest nested editable CSS class naming convention (see ckeditor/ckeditor5#578).
---
Requires: https://github.com/ckeditor/ckeditor5-widget/pull/36
=> Other: Updated the classic editor and the editorui styles to the latest nested editable CSS class naming convention

theme/ckeditor5-engine/placeholder.css, theme/ckeditor5-image/imageuploadprogress.css, theme/ckeditor5-link/link.css, theme/ckeditor5-widget/widget.css
Internal: `.ck` class should not be added to elements inside editor editable.
---
Part of https://github.com/ckeditor/ckeditor5/issues/936
=> .ck class should not be added to elements inside editor editable

theme/ckeditor5-image/imageuploadicon.css
Fix: Added missing box-sizing to the successful upload icon. Closes ckeditor/ckeditor5/issues/1095.
=> Added missing box-sizing for the upload icon pseudoelement.

theme/ckeditor5-ui/components/button/switchbutton.css
Fix: Faster toggle button animation. Closes #183.
---
100ms makes a difference :)
=> Faster toggle button animation

tests/manual/iconset.js
Tests: Extended the iconset test with heading levels 4-6 icons (see ckeditor/ckeditor5-heading#112).
=> t/ckeditor/ckeditor5-heading/112: Extended the iconset test with heading levels 4-6 icons.

theme/ckeditor5-image/textalternativeform.css, theme/ckeditor5-link/linkactions.css, theme/ckeditor5-link/linkform.css, theme/ckeditor5-media-embed/mediaform.css, theme/mixins/_rwd.css
Feature: Introduced the `ck-media-phone` RWD mixin that outputs a `@media` query. Improved responsiveness of media embed, link, and image form views in narrow viewports (see ckeditor/ckeditor5#416).
---
A part of https://github.com/ckeditor/ckeditor5/pull/1299.
=> t/ckeditor5/416: Feature: Introduced the ck-media-phone RWD mixin; improved responsive of various views

theme/ckeditor5-widget/widget.css
Other: Moved widget spacing styles to respective content styles in packages. Closes #209.
---
[Constellation](https://github.com/ckeditor/ckeditor5/compare/t/ckeditor5-theme-lark/209?expand=1).
Requires:
* https://github.com/ckeditor/ckeditor5-media-embed/pull/63
* https://github.com/ckeditor/ckeditor5-image/pull/249
=> Moved widget spacing styles to respective content styles in packages.

tests/manual/iconset.js
Tests: Update manual tests to reflect changes in ui library.
---
* After ui PR: https://github.com/ckeditor/ckeditor5-ui/pull/456
=> Update manual tests to reflect changes in ui library.

theme/ckeditor5-ui/globals/_colors.css, theme/ckeditor5-ui/globals/_shadow.css
Other: Introduced a new `--ck-drop-shadow-active` CSS variable.
---
This new shadow variable is neccessary for our new comments and suggestions design.
=> Introduced new box-shadow CSS variable.

theme/ckeditor5-mention/mentionediting.css
Internal: Introduce mention feature styles.
---
* Required for https://github.com/ckeditor/ckeditor5-mention/pull/2
=> Move mention CSS definitions to theme lark.

theme/ckeditor5-ui/components/panel/balloonrotator.css
Feature: Introduced rotatable panels styles for ContextualBalloon. 
---
Requires: https://github.com/ckeditor/ckeditor5-ui/pull/493
=> Introduced rotatable panels styles for ContextualBalloon

theme/ckeditor5-ui/components/panel/balloonrotator.css, theme/ckeditor5-ui/components/panel/fakepanel.css
Feature: Introduced styles for `ck-fake-panel`. Part of  https://github.com/ckeditor/ckeditor5-ui/issues/501.
---
Required: https://github.com/ckeditor/ckeditor5-ui/pull/498
=> Introduced FakePanels styles for ContextualBalloon

theme/ckeditor5-ui/components/panel/fakepanel.css
Internal: Updated the license header. See ckeditor/ckeditor5#1557. [skip ci]
=> Updated the license header

theme/ckeditor5-ui/components/colorgrid/colorgrid.css
Other: Correct class name related to change in ColorGridView.
---
* PR required by ckeditor/ckeditor5-font#39
=> Correct class name related to change in ColorGridView

package.json
Internal: Add missing dev dependencies.
---
* The indent plugin is missing.
=> Add missing dev dependencies.

theme/ckeditor5-horizontal-rule/horizontalrule.css
Internal: Introduced horizontal-rule styles. See https://github.com/ckeditor/ckeditor5-horizontal-rule/issues/8.
---
Required: https://github.com/ckeditor/ckeditor5-horizontal-rule/pull/9
=> Introduced horizontal-rule styles.

theme/ckeditor5-ui/components/toolbar/toolbar.css
Other: Adjusted toolbar styles to allow automatic items grouping (see ckeditor/ckeditor5#416).
---
Part of https://github.com/ckeditor/ckeditor5-ui/pull/523.
=> T/ckeditor5/416d: Adjusted toolbar styles to allow automatic items grouping

theme/ckeditor5-horizontal-line/horizontalline.css
Internal: Aligned Horizontal Line CSS to changes in the plugin name. Closes ckeditor/ckeditor5#5592.
=> Aligned Horizontal Line CSS to changes in the plugin name

docs/framework/guides/theme-customization.md
add colors for .ck-splitbutton to use Track Changes with dark theme
=> Add  .ck-splitbutton to Theme customization

package.json, tests/manual/iconset.js, theme/ckeditor5-code-block/codeblock.css
Feature: Added styles for the code block feature UI (see ckeditor/ckeditor5#436).
---
Requires https://github.com/ckeditor/ckeditor5-code-block/pull/1.
=> t/ckeditor5/436: Added styles for the code block feature

theme/ckeditor5-ui/components/labeledview/labeledview.css
Feature: Added styles for the LabeledView (see https://github.com/ckeditor/ckeditor5-table/pull/227).
---
Part of https://github.com/ckeditor/ckeditor5-table/pull/227.
=> i/6049: Added styles for the LabeledView.

theme/ckeditor5-table/tableselection.css
Features: Brought styles for selected table cells (multi-cell selection) (see ckeditor/ckeditor5#6114).
---
Requires https://github.com/ckeditor/ckeditor5-table/pull/257.
=> i/6114: Brought styles for selected table cells

theme/ckeditor5-table/tableselection.css
Internal: Improved styles for cell selection. See ckeditor/ckeditor5#6114.
=> Styles for table cell selection
